### ISSUE TITLE
[Feature Request] Add the app to the F-Droid repositories

### ISSUE THREAD

**Issue by artur-py** [jerryhcooke/smouldering_durtles#31]
I'd like to propose the addition of this app to the [official F-Droid repository](https://f-droid.org/) , the largest reposity of Free, Libre and Open Source (FLOSS) Android apps.
[Here's a guide on how to do it](https://f-droid.org/en/docs/Inclusion_How-To/).

**Comment by idrilirdi** [comment]
I just came here to suggest the same thing :)

**Comment by jerryhcooke** [comment]
Sorry for not having looked at this as of yet, I'll admit I don't know much about F-Droid, so will take a look :)

**Comment by jemsurfer** [comment]
I created an issue on f-droid's requests for packaging: https://gitlab.com/fdroid/rfp/-/issues/2606. Hope that helps

**Comment by jerryhcooke** [comment]
Hi @jemsurfer - sorry I've not done more for this yet - I need to implement Fastlane folder structures for their listing requirements and it's not something I've found time to do 😬

**Comment by jerryhcooke** [comment]
Hey @artur-py, @idrilirdi, and @jemsurfer 

Sorry there's been such a delay in this, I've had a hell of a year and getting my head around the requirements was melting my limited spoons away. I'm happy to confirm that after a couple of days of playing whack-a-mole with version and tag handling, etc.  my merge request for app inclusion is now passing all pipeline checks and so hopefully it'll end up in F-Droid soon!

**Comment by IzzySoft** [comment]
You might have missed that since 2023-12-21, your app is already [available at IzzyOnDroid](https://apt.izzysoft.de/packages/com.smouldering_durtles.wk) :wink: However, since v1.1.2, the APKs attached at your releases are signed using a debug key, so updates are no longer possible (v1.1.1 was the last one with a properly signed APK; debug keys are a security risk, they are not intended for signing release APKs). Could you please fix that? Thanks in advance!

**Comment by IzzySoft** [comment]
Btw: I checked if your app can be established as [Reproducible Build](https://reproducible-builds.org/) (something F-Droid will ask for as well) – but unfortunately it failed RB. Here's the diff of the APKs:

```diff
  -rw----     0.0 fat     2072 b-      807 defN 1981-01-01 01:01:02 d1c9fbb4 res/2j.xml
- -rw----     0.0 fat    13558 b-    13558 stor 1981-01-01 01:01:02 b72e27fa res/2s.png
+ -rw----     0.0 fat    13558 b-    13558 stor 1981-01-01 01:01:02 3eba5d8c res/2s.png
  -rw----     0.0 fat      541 b-      541 stor 1981-01-01 01:01:02 c5fedfaf res/33.9.png
  -rw----     0.0 fat     1056 b-      501 defN 1981-01-01 01:01:02 26dd148f res/3A.xml
  -rw----     0.0 fat    40055 b-     7416 defN 1981-01-01 01:01:02 568b10c7 res/3Q.json
@@ -137,7 +137,7 @@
  -rw----     0.0 fat      756 b-      291 defN 1981-01-01 01:01:02 387b678e res/4u.xml
  -rw----     0.0 fat      272 b-      272 stor 1981-01-01 01:01:02 e0e00b8a res/5D.9.png
  -rw----     0.0 fat     2652 b-      917 defN 1981-01-01 01:01:02 1f38d1ea res/5D.xml
- -rw----     0.0 fat    10731 b-    10731 stor 1981-01-01 01:01:02 d0c7a695 res/5L.png
+ -rw----     0.0 fat    10728 b-    10728 stor 1981-01-01 01:01:02 ee3fd473 res/5L.png
  -rw----     0.0 fat   163533 b-    31562 defN 1981-01-01 01:01:02 2f127b5c res/5P.json
  -rw----     0.0 fat      852 b-      377 defN 1981-01-01 01:01:02 ad0cac1a res/5T.xml
  -rw----     0.0 fat      396 b-      396 stor 1981-01-01 01:01:02 be21c0b7 res/5U.png
@@ -217,7 +217,7 @@
  -rw----     0.0 fat     7588 b-     1639 defN 1981-01-01 01:01:02 c0824623 res/DZ1.xml
  -rw----     0.0 fat      320 b-      190 defN 1981-01-01 01:01:02 b0798f16 res/DZ2.xml
  -rw----     0.0 fat      178 b-      178 stor 1981-01-01 01:01:02 c56f26da res/D_.9.png
- -rw----     0.0 fat  1547668 b-   848366 defN 1981-01-01 01:01:02 452aec01 res/E3.ttf
+ -rw----     0.0 fat  1547668 b-   848365 defN 1981-01-01 01:01:02 452aec01 res/E3.ttf
  -rw----     0.0 fat      200 b-      200 stor 1981-01-01 01:01:02 3023e3da res/EA.9.png
  -rw----     0.0 fat      310 b-      310 stor 1981-01-01 01:01:02 40bc4240 res/EP.png
  -rw----     0.0 fat     2392 b-      677 defN 1981-01-01 01:01:02 8a612f30 res/EV.xml
@@ -350,7 +350,7 @@
  -rw----     0.0 fat     9101 b-     9101 stor 1981-01-01 01:01:02 3b0848ae res/UG.png
  -rw----     0.0 fat      422 b-      422 stor 1981-01-01 01:01:02 394ef93c res/UR.png
  -rw----     0.0 fat      508 b-      259 defN 1981-01-01 01:01:02 af7e1787 res/UX.xml
- -rw----     0.0 fat     7360 b-     7360 stor 1981-01-01 01:01:02 1d47ab14 res/Ul.png
+ -rw----     0.0 fat     7361 b-     7361 stor 1981-01-01 01:01:02 9df7a586 res/Ul.png
  -rw----     0.0 fat      864 b-      446 defN 1981-01-01 01:01:02 024fb992 res/V1.xml
  -rw----     0.0 fat      304 b-      174 defN 1981-01-01 01:01:02 1ab1b25f res/V7.xml
  -rw----     0.0 fat      596 b-      323 defN 1981-01-01 01:01:02 24e7e761 res/VH.xml
@@ -395,7 +395,7 @@
  -rw----     0.0 fat     2200 b-      801 defN 1981-01-01 01:01:02 3a67abef res/_Q.xml
  -rw----     0.0 fat      940 b-      456 defN 1981-01-01 01:01:02 06d50ef6 res/_d.xml
  -rw----     0.0 fat      316 b-      187 defN 1981-01-01 01:01:02 45cb4331 res/_o.xml
- -rw----     0.0 fat    15168 b-    15168 stor 1981-01-01 01:01:02 7bf95d78 res/_q.png
+ -rw----     0.0 fat    15169 b-    15169 stor 1981-01-01 01:01:02 b8eeaacb res/_q.png
  -rw----     0.0 fat      173 b-      173 stor 1981-01-01 01:01:02 0b399ef9 res/_q1.png
  -rw----     0.0 fat      612 b-      311 defN 1981-01-01 01:01:02 9704f384 res/_y.xml
  -rw----     0.0 fat     1228 b-      539 defN 1981-01-01 01:01:02 7283c055 res/a0.xml
@@ -472,7 +472,7 @@
  -rw----     0.0 fat      764 b-      430 defN 1981-01-01 01:01:02 83123fec res/fN.xml
  -rw----     0.0 fat    12075 b-    12075 stor 1981-01-01 01:01:02 37b342d7 res/fO.png
  -rw----     0.0 fat      544 b-      300 defN 1981-01-01 01:01:02 610b9501 res/fS.xml
- -rw----     0.0 fat  2558160 b-  1576577 defN 1981-01-01 01:01:02 d273d2ab res/fT.ttf
+ -rw----     0.0 fat  2558160 b-  1576575 defN 1981-01-01 01:01:02 d273d2ab res/fT.ttf
  -rw----     0.0 fat     3216 b-     1035 defN 1981-01-01 01:01:02 27cd8535 res/fY.xml
  -rw----     0.0 fat      585 b-      585 stor 1981-01-01 01:01:02 1361e44f res/g-.png
  -rw----     0.0 fat     2872 b-      805 defN 1981-01-01 01:01:02 77b3873f res/g-.xml
@@ -505,7 +505,7 @@
  -rw----     0.0 fat      785 b-      785 stor 1981-01-01 01:01:02 1cea0e0c res/j4.png
  -rw----     0.0 fat     4980 b-     1458 defN 1981-01-01 01:01:02 dc3ccbc2 res/j5.xml
  -rw----     0.0 fat      464 b-      245 defN 1981-01-01 01:01:02 30134a69 res/j6.xml
- -rw----     0.0 fat    15168 b-    15168 stor 1981-01-01 01:01:02 7bf95d78 res/jJ.png
+ -rw----     0.0 fat    15169 b-    15169 stor 1981-01-01 01:01:02 b8eeaacb res/jJ.png
  -rw----     0.0 fat     1808 b-      626 defN 1981-01-01 01:01:02 35387162 res/jK.xml
  -rw----     0.0 fat      236 b-      236 stor 1981-01-01 01:01:02 585bf0cc res/jS.9.png
  -rw----     0.0 fat      167 b-      167 stor 1981-01-01 01:01:02 35642324 res/jS1.9.png
@@ -519,7 +519,7 @@
  -rw----     0.0 fat      187 b-      187 stor 1981-01-01 01:01:02 65805944 res/kG.png
  -rw----     0.0 fat      208 b-      208 stor 1981-01-01 01:01:02 a531b28b res/kJ.9.png
  -rw----     0.0 fat      592 b-      321 defN 1981-01-01 01:01:02 a5013aa7 res/kR.xml
- -rw----     0.0 fat  1407252 b-   756224 defN 1981-01-01 01:01:02 cb4d07f6 res/kX.ttf
+ -rw----     0.0 fat  1407252 b-   756219 defN 1981-01-01 01:01:02 cb4d07f6 res/kX.ttf
  -rw----     0.0 fat      508 b-      258 defN 1981-01-01 01:01:02 44f18136 res/k_.xml
  -rw----     0.0 fat     2520 b-      731 defN 1981-01-01 01:01:02 a46501b9 res/kj.xml
  -rw----     0.0 fat      816 b-      342 defN 1981-01-01 01:01:02 4da85ede res/kn.xml
@@ -529,14 +529,14 @@
  -rw----     0.0 fat      194 b-      194 stor 1981-01-01 01:01:02 945f2990 res/lP.9.png
  -rw----     0.0 fat      440 b-      260 defN 1981-01-01 01:01:02 9127c147 res/lR.xml
  -rw----     0.0 fat     1656 b-      653 defN 1981-01-01 01:01:02 d948aa68 res/lf.xml
- -rw----     0.0 fat    35125 b-    35125 stor 1981-01-01 01:01:02 8b15407b res/lm.png
+ -rw----     0.0 fat    35124 b-    35124 stor 1981-01-01 01:01:02 cd4ec81a res/lm.png
  -rw----     0.0 fat     1292 b-      511 defN 1981-01-01 01:01:02 82b38f58 res/ls.xml
  -rw----     0.0 fat      272 b-      272 stor 1981-01-01 01:01:02 58089ef9 res/ly.png
  -rw----     0.0 fat    11242 b-    11242 stor 1981-01-01 01:01:02 ae1a6627 res/lz.png
  -rw----     0.0 fat      267 b-      267 stor 1981-01-01 01:01:02 f1f6a033 res/m0.png
  -rw----     0.0 fat     2028 b-      624 defN 1981-01-01 01:01:02 5ce03894 res/m6.xml
  -rw----     0.0 fat     3004 b-      922 defN 1981-01-01 01:01:02 d0643d58 res/mI.xml
- -rw----     0.0 fat    13558 b-    13558 stor 1981-01-01 01:01:02 b72e27fa res/mU.png
+ -rw----     0.0 fat    13558 b-    13558 stor 1981-01-01 01:01:02 3eba5d8c res/mU.png
  -rw----     0.0 fat      345 b-      345 stor 1981-01-01 01:01:02 bd28c868 res/mm.9.png
  -rw----     0.0 fat      207 b-      207 stor 1981-01-01 01:01:02 3a5ce84d res/nI.9.png
  -rw----     0.0 fat     1504 b-      626 defN 1981-01-01 01:01:02 8970683b res/nP.xml
@@ -572,7 +572,7 @@
  -rw----     0.0 fat      676 b-      374 defN 1981-01-01 01:01:02 80ef55a4 res/qG.xml
  -rw----     0.0 fat     2289 b-     2289 stor 1981-01-01 01:01:02 6dbbeb21 res/qY.png
  -rw----     0.0 fat     2608 b-      997 defN 1981-01-01 01:01:02 6b3e5fc7 res/qa.xml
- -rw----     0.0 fat     7360 b-     7360 stor 1981-01-01 01:01:02 1d47ab14 res/qe.png
+ -rw----     0.0 fat     7361 b-     7361 stor 1981-01-01 01:01:02 9df7a586 res/qe.png
  -rw----     0.0 fat      197 b-      197 stor 1981-01-01 01:01:02 a759a25f res/qp.png
  -rw----     0.0 fat     2780 b-      741 defN 1981-01-01 01:01:02 8dcc80d9 res/qx.xml
  -rw----     0.0 fat     1656 b-      430 defN 1981-01-01 01:01:02 40c7d103 res/qz.xml
@@ -652,8 +652,8 @@
  -rw----     0.0 fat      960 b-      377 defN 1981-01-01 01:01:02 9ed4c336 res/xu.xml
  -rw----     0.0 fat      396 b-      228 defN 1981-01-01 01:01:02 cc6ffadf res/y-.xml
  -rw----     0.0 fat      388 b-      216 defN 1981-01-01 01:01:02 6270df64 res/y4.xml
- -rw----     0.0 fat  8240138 b-  2938739 defN 1981-01-01 01:01:02 84316cfe res/yB.json
- -rw----     0.0 fat  1840784 b-  1071800 defN 1981-01-01 01:01:02 47b577b9 res/yC.ttf
+ -rw----     0.0 fat  8240138 b-  2938738 defN 1981-01-01 01:01:02 84316cfe res/yB.json
+ -rw----     0.0 fat  1840784 b-  1071802 defN 1981-01-01 01:01:02 47b577b9 res/yC.ttf
  -rw----     0.0 fat      184 b-      184 stor 1981-01-01 01:01:02 d42327b8 res/yH.9.png
```

As you can see, it's mostly PNG files. Are you maybe using something like PNGCrunch, or generate them from vector drawables? Those methods are non-deterministic, and thus will make RB fail, see e.g. [image compression](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Reproducible-Builds#compressing-images) in our wiki.

The next group are TTFs. Are those generated at build time? Same question for the JSON files, I wonder why those differ. Everything depending on build time will cause RB to fail (if a build performed a week later gets different files, for example).

Some of the differences seem to be only in compression, e.g.

```diff
  perms       ver FSys Size    tt CompSize Algo Timestamp           CRC      FileName
  ----------+----+----+-------+--+--------+----+-------------------+--------+-----------
- -rw----     0.0 fat  1407252 b-   756224 defN 1981-01-01 01:01:02 cb4d07f6 res/kX.ttf
+ -rw----     0.0 fat  1407252 b-   756219 defN 1981-01-01 01:01:02 cb4d07f6 res/kX.ttf
```

(I've added a header to explain the columns). Here you see the uncompressed size is identical, so is the checksum (CRC) – but the compressed size differs slightly. What system did you build your APK on (OS, JDK etc)?

**Comment by IzzySoft** [comment]
Btw, your fastlane tree lacks the mandatory `en-US` locale – which is used as fallback for all missing locales. You might wish to rename `en-GB` correspondingly, or add `en-US` additionally.

**Comment by IzzySoft** [comment]
I've just checked v1.2.0 you just released: not RB, still the same issues (just to let you know in case you expected some of them solved).

**Comment by jerryhcooke** [comment]
Hi @IzzySoft - I'll be frank and say I've no idea where those files are coming from or why the difference. It's possible it's because I committed the tag after I built the APK. I made sure to commit the tag first this time (at least, I'm fairly certain I did) so may be okay now? 

To answer your question from earlier, I'm on macOS Sonoma with Android Studio Ladybug 2024.2.1 Patch 3

I'll amend the fast lane config, thank you for the note.

**Comment by IzzySoft** [comment]
> I've no idea where those files are coming from or why the difference.

The PNG files could be auto-generated (from vector graphics), or compressed during build (e.g. PNGCrunch; the link above details both). The TTF files most likely come from `app/src/main/res/font` and are processed in some way by the build, too (I'm no Android dev, so I have no clue how that might happen – but I've seen this "renaming" quite a few times. No idea, though, what "optimization" might kick in there during the build).

> I committed the tag after I built the APK

As long as you've built the APK from a clean tree **at the commit** (i.e. first `git commit`, then (clean and then) build), that should make no difference: the tag is just a pointer, pointing to the commit. You seem to have disabled `vcsInfo` (which would have embedded the commit hash in the APK, which is quite helpful for debugging such issues), so I cannot tell (are you building from inside the git repo at all, or from a separate tree outside it?).

> so may be okay now?

Afraid not: results for v1.2.1 still look the same.

> I'm on macOS Sonoma with Android Studio Ladybug 2024.2.1 Patch 3

OK, so at least a Posix system (and we won't have to deal with Windows issues). Can you look into the Studio config what JDK it's using? We use OpenJDK-17 here by default (but can switch to 21 or even 11 if needed). Studio loves to default to Jetbrains SDK, which sometimes causes issues with RB; it's possible to download and use OpenJDK from inside Studio, though, I've been told.

> I'll amend the fast lane config, thank you for the note.

Great, thanks!

**Comment by jerryhcooke** [comment]
> The PNG files could be auto-generated (from vector graphics), or compressed during build

Possibly, but I've no idea where if they are. I've added the cruncherEnabled = false and vectorDrawables.generatedDensities = [] bit to the build config and can't see any issues when building and testing, so it may be not required anyway. There's no PNGs in the source other than the screenshots for fastlane, so I can only assume they're the radicals that get generated. 

> You seem to have disabled vcsInfo

I've looked around a fair bit and can't see any reference to this in my Android Studio version.

> Can you look into the Studio config what JDK it's using? We use OpenJDK-17 here by default

I was using Correto-19, I'll drop down to 17.

**Comment by IzzySoft** [comment]
> I've added the cruncherEnabled = false and vectorDrawables.generatedDensities = [] bit to the build config and can't see any issues when building and testing, so it may be not required anyway.

You should not see any issues when building and testing. But it might make the difference with reproducible builds. Can you provide me an APK with those settings, built from a clean tree at a commit you name? I could the cross-check if it did the trick.

> I've looked around a fair bit and can't see any reference to this in my Android Studio version.

I could not find it either, and it's enabled by default. Are you building from within the git tree (i.e. the one with the `.git/` directory at its root) – or from an "export" with out the `.git/` directory? The latter would explain its absence.

> I was using Correto-19, I'll drop down to 17.

Ah! Thanks and thanks! Yes, that explains. with 18/19 built APKs we had issues in the past, which were solved the very same way: either by dropping down to 17, or by jumping up to 21.

**Comment by jerryhcooke** [comment]
> Can you provide me an APK with those settings, built from a clean tree at a commit you name? 

The 1.2.3 version in the most recent release with the v1.2.3 tag is built cleanly with those settings. 

> Are you building from within the git tree (i.e. the one with the .git/ directory at its root).

The project directory contains the .git/ at root, so it should be within.

**Comment by IzzySoft** [comment]
Thanks! I can confirm the differences in the graphic files are gone. Only those in the font files and in one JSON file remain:

```diff
  -rw----     0.0 fat      178 b-      178 stor 1981-01-01 01:01:02 c56f26da res/D_.9.png
- -rw----     0.0 fat  1547668 b-   848366 defN 1981-01-01 01:01:02 452aec01 res/E3.ttf
+ -rw----     0.0 fat  1547668 b-   848365 defN 1981-01-01 01:01:02 452aec01 res/E3.ttf
  -rw----     0.0 fat      200 b-      200 stor 1981-01-01 01:01:02 3023e3da res/EA.9.png
  -rw----     0.0 fat      310 b-      310 stor 1981-01-01 01:01:02 40bc4240 res/EP.png
  -rw----     0.0 fat     2392 b-      677 defN 1981-01-01 01:01:02 8a612f30 res/EV.xml
@@ -472,7 +472,7 @@
  -rw----     0.0 fat      764 b-      430 defN 1981-01-01 01:01:02 83123fec res/fN.xml
  -rw----     0.0 fat    12075 b-    12075 stor 1981-01-01 01:01:02 37b342d7 res/fO.png
  -rw----     0.0 fat      544 b-      300 defN 1981-01-01 01:01:02 610b9501 res/fS.xml
- -rw----     0.0 fat  2558160 b-  1576577 defN 1981-01-01 01:01:02 d273d2ab res/fT.ttf
+ -rw----     0.0 fat  2558160 b-  1576575 defN 1981-01-01 01:01:02 d273d2ab res/fT.ttf
  -rw----     0.0 fat     3216 b-     1035 defN 1981-01-01 01:01:02 27cd8535 res/fY.xml
  -rw----     0.0 fat      585 b-      585 stor 1981-01-01 01:01:02 1361e44f res/g-.png
  -rw----     0.0 fat     2872 b-      805 defN 1981-01-01 01:01:02 77b3873f res/g-.xml
@@ -519,7 +519,7 @@
  -rw----     0.0 fat      852 b-      852 stor 1981-01-01 01:01:02 e492dfd2 res/kG.png
  -rw----     0.0 fat      208 b-      208 stor 1981-01-01 01:01:02 a531b28b res/kJ.9.png
  -rw----     0.0 fat      592 b-      321 defN 1981-01-01 01:01:02 a5013aa7 res/kR.xml
- -rw----     0.0 fat  1407252 b-   756224 defN 1981-01-01 01:01:02 cb4d07f6 res/kX.ttf
+ -rw----     0.0 fat  1407252 b-   756219 defN 1981-01-01 01:01:02 cb4d07f6 res/kX.ttf
  -rw----     0.0 fat      508 b-      258 defN 1981-01-01 01:01:02 44f18136 res/k_.xml
  -rw----     0.0 fat     2520 b-      731 defN 1981-01-01 01:01:02 a46501b9 res/kj.xml
  -rw----     0.0 fat      816 b-      342 defN 1981-01-01 01:01:02 4da85ede res/kn.xml
@@ -652,8 +652,8 @@
  -rw----     0.0 fat      960 b-      377 defN 1981-01-01 01:01:02 9ed4c336 res/xu.xml
  -rw----     0.0 fat      396 b-      228 defN 1981-01-01 01:01:02 cc6ffadf res/y-.xml
  -rw----     0.0 fat      388 b-      216 defN 1981-01-01 01:01:02 6270df64 res/y4.xml
- -rw----     0.0 fat  8240138 b-  2938739 defN 1981-01-01 01:01:02 84316cfe res/yB.json
- -rw----     0.0 fat  1840784 b-  1071800 defN 1981-01-01 01:01:02 47b577b9 res/yC.ttf
+ -rw----     0.0 fat  8240138 b-  2938738 defN 1981-01-01 01:01:02 84316cfe res/yB.json
+ -rw----     0.0 fat  1840784 b-  1071802 defN 1981-01-01 01:01:02 47b577b9 res/yC.ttf
  -rw----     0.0 fat      184 b-      184 stor 1981-01-01 01:01:02 d42327b8 res/yH.9.png
```

My guess concerning the JSON is it's something generated at runtime? That makes RB impossible then. The TTFs confuse me: they seem to be identical before compression (same size & CRC), but compressed size differs. Are you building on Fedora or Arch maybe, and use `zlib-ng` instead of `zlib`?

```
$ list-compression-levels *unsigned.apk res/E3.ttf
filename='res/E3.ttf' compresslevel=9

$ list-compression-levels *upstream.apk res/E3.ttf
Traceback (most recent call last):
  File "reproducible-apk-tools/list-compresslevel.py", line 144, in <module>
    list_compresslevel(args.apk, *args.patterns, levels=clevels)
  File "reproducible-apk-tools/list-compresslevel.py", line 52, in list_compresslevel
    raise Error(f"Unable to determine compresslevel for {info.filename!r}")
__main__.Error: Unable to determine compresslevel for 'res/E3.ttf'
```
Not being able to even read the compression level _might_ be an indicator for something like that.

**Comment by jerryhcooke** [comment]
> My guess concerning the JSON is it's something generated at runtime?

I've honestly got no idea, I'm aware there's a font import mechanism for custom fonts, but in terms of compression your guess is as good as mine. That bit of code is preexisting, before I forked the abandoned project. 

> Are you building on Fedora or Arch maybe, and use zlib-ng instead of zlib?

Nope, only ever in macOS, I don't build on any platform but my home Mac Mini, though Android Studio, typically.

**Comment by IzzySoft** [comment]
Umpf. Thanks, but that leaves me clueless then. I guess those fonts are needed for Kanji, so they cannot be simply "disposed". No idea what that JSON is about at all. And I'm no Android dev, so I can't tell about rewriting that font-import stuff. As pointed out, the font files themselves are identical, just the compression does not match. And I do not know enough to say what settings might affect this.

**Comment by IzzySoft** [comment]
Found something for the TTF:

```gradle
aaptOptions {
    noCompress 'ttf', '.ttf'
}
```

which then would only leave the JSON part…

**Comment by IzzySoft** [comment]
@jerryhcooke you've closed this issue with a PR adding the F-Droid badge (missing the IoD one, as outlined there). But the RB part is still unsolved. Shall I open a new issue for that? And would you copy-paste the badge code I've mentioned in the linked PR to the Readme?

**Comment by IzzySoft** [comment]
@jerryhcooke so what are we doing now concerning RB? Shall we drop it from our "pending" list, or are you still interested getting the app RB?
